archful = false
archive_name = "/home/andrew/Projects/Terminal/Test_TUI/dist/test_tui-1.0.0.tar.gz"
extras = []
license_files_present = false
name = "test-tui"
python_name = "python-test-tui"
scripts = [
    "test_tui-cmd",
]
source = "local"
summary = "A centered red text terminal user interface built with blessed"
top_level_modules = [
    "__init__",
    "main",
]
url = "..."
version = "1.0.0"
